apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-cnpg-trimmed-password-secret # A clear, specific name
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: dev-cnpg-secret-store-store # Your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: dev-cnpg-trimmed-password-secret # Name of the Kubernetes Secret to create
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        DATABASE_URL: |
          postgres://{{ .databaseUserName }}:{{ .cnpgPassword }}@{{ .databaseHost }}:{{ .databasePort }}/{{ .databaseName }}
  dataFrom:
    - extract:
        key: db
